### ISSUE TITLE
Can I somehow Use Selenium Headless Dynamic WebScraping or any other Dynamic WebScraping Library?

### ISSUE THREAD

**Issue by TejasDhanda-L11** [jaydangar/chaquopy_flutter#10]
* Combination of requests+BeautifulSoup4 can't perform dynamic Actions.
*

**Comment by jaydangar** [comment]
As this is plugin uses chaquopy sdk, it's better to use [this](https://chaquo.com/chaquopy/doc/current/android.html) thread to  check for supported packages.
