### ISSUE TITLE
Package doesn't support null safety. 

### ISSUE THREAD

**Issue by TejasDhanda-L11** [jaydangar/chaquopy_flutter#11]
Bro, thanks for such a cool package.
As you may know, Null safety is default now and helps to tackle so many of the annoying errors.
I would love it if you can migrate it to null safety (I would but I have just started leaning dart very recently on my own so I don't understand a lot of the stuff)

**Comment by jaydangar** [comment]
I am currently working on null safety support. if you like the plugin kindly star this repo, it would be really motivative for me. thanks.

**Comment by jaydangar** [comment]
@TejasDhanda-L11 Just a quick update, I have just added the null safety feature and uploaded the new version of this plugin. So, once review is finished it'll be available for use.

**Comment by TejasDhanda-L11** [comment]
That's so great man.

Just as a student, who reviews it (some kind of cool computer code which runs code with different values for variables in environment or other developers)?

**Comment by jaydangar** [comment]
right now I am the only man who's maintaining this plugin.
