### ISSUE TITLE
Offering help for the project

### ISSUE THREAD

**Issue by TejasDhanda-L11** [jaydangar/chaquopy_flutter#12]
Man, the reason I love this project is because I tried for months to find something like this.
It unlocks the power of python into Android with flutter.

I couldn't find the any method.

I want to contribute to this project.

Could you possibly please refer me how to learn this kind of stuff.
I am in 11th and so have no college to learn it from, so could you recommend any YouTube playlist or udemy course or coursera or something.

*You can also earn on YouTube (as Passive Income) by uploading how you achieved it.

**Comment by jaydangar** [comment]
@TejasDhanda-L11 I learned it from myself. Online courses will create a base for you, but moving further you need zeal and passion. I am really happy to hear you liked the package and it does indeed saves a lot of developer's time for this particular integration part running python code on flutter apps. 

You can definitely contribute to this project, but before that i would advise you to learn basics of python, flutter and native android app development, which will surely beneficial for you. thanks again for the kind words.

**Comment by TejasDhanda-L11** [comment]
I am really good at python (as far as I know).

I am new to mobile development (though I am able to create some good apps from flutter).

For native part, I am thinking to learn it, but am confused to choose C++ or Java to go ahead with it.
And could you possibly recommend any good YouTube playlist to learn from (or udemy, Coursera etc courses) which are highly up to date.

I wouldn't mind if you don't because it might be time wasting to you.
And thanks for giving me an idea of steps ahead.

**Comment by jaydangar** [comment]
@TejasDhanda-L11 Definitely you can help if you have sound knowledge of python. You can contribute on adding new features such as integration of OpenCV,  Matplotlib, etc which is the top priority. kindly email me your details and we'll connect. Thanks for showing the interest.

**Comment by TejasDhanda-L11** [comment]
email: tejas11personal@gmail.com

I wanted to add a can scanning component in my app but it wasn't possible until I learned Java or C++ to use OpenCV so I would be really glad to help you out with it.

*I am not experienced in github and collaboration kind of stuff, so I would need your help in that.
