### ISSUE TITLE
Call python functions from main.dart

### ISSUE THREAD

**Issue by anshul798** [jaydangar/chaquopy_flutter#13]
Is there a way to call functions of any python file stored in app/src/main/python from main.dart?
I can't use text python file as I need to pass data to those functions after calling an API.

**Comment by jaydangar** [comment]
@anshul798 you can easily read a text file using this plugin. Chaquopy official SDK provided the documentation for it, which you can find [here](https://chaquo.com/chaquopy/doc/current/android.html), check Data files Section, which might help you resolve your query.
