### ISSUE TITLE
Reading a file 

### ISSUE THREAD

**Issue by Douglas47** [jaydangar/chaquopy_flutter#16]
I already asked this in other Issue (https://github.com/jaydangar/chaquopy_flutter/issues/3), but as it was closed and I thought it was better to create another one to discuss a solution.

My problem is that I want to read a csv file with my python script, but i cannot find the path to the file.

My python script is in: `/android/app/src/main/python/project_files/run.py`
The csv is in the same directory: `/android/app/src/main/python/project_files/tmp.csv`

This is my code:

```
def test_pandas():
   csvname = os.path.join(os.path.dirname(__file__), "tmp.csv")
   df = pd.read_csv(csvname)
   return df 
```

I tried to use these other codes instead of `os.path.join(os.path.dirname(__file__), "tmp.csv")`

```
join(os.getcwd())
join(sys.argv[0])
join(os.path.dirname(os.path.realpath('__file__')))
```

but none of them worked. I always get these answers:

`name '__file__' is not defined `   with the original option

or

`[Error 2] No such file or directory: 'tmp.csv'`   with the alternatives

When I run `print(os.getcwd())` on run.py, show me that I'm at `/`

**Comment by jaydangar** [comment]
@Douglas47 Can you try this code shown in this [video](https://www.youtube.com/watch?v=m_vV5ZKBuNg)?

**Comment by Douglas47** [comment]
> @Douglas47 Can you try this code shown in this [video](https://www.youtube.com/watch?v=m_vV5ZKBuNg)?

The code shown in this video is in Java. I'm trying to run python with Dart/Flutter.

If I'm not wrong, in Java is created a Python instance, but in Dart/Flutter, the App reads the code in string format with Chaquopy.executeCode(). I don't know what the impact of this is on reading a file within the project. My other python functions work, only those that need a file are broken.

I tried the `join(dirname(__file__), 'tmp.csv')` path like he/she does, but the error `name '__file__' is not defined` remains

**Comment by jaydangar** [comment]
You can search more about this issue in chaquopy's [official GitHub repo](https://github.com/chaquo/chaquopy/issues). I hope there you can find solution for the issue you are facing.
