### ISSUE TITLE
msg's executing time is too long 

### ISSUE THREAD

**Issue by Muhd-Faiq** [jaydangar/chaquopy_flutter#18]
Chaquopy version

'com.chaquo.python:gradle:9.1.0'
Devices or emulators where the issue happens

I am using my android devices which realme 5 pro.
Relevant parts of your code
Describe your issue

After cloning your code from https://github.com/jaydangar/chaquopy_flutter and run it on my device, I try to execute command 'from deepface import DeepFace DeepFace.stream()' , this command will download the library first then it will run the DeepFace.stream. But while downloading, it suddenly stop running and it print error message which stated below:

W/python.stderr(17710): 15%|█▌ | 82.8M/539M [00:05<00:28, 16.0MB/s]
W/python.stderr(17710):
E/ANR_LOG (17710): >>> msg's executing time is too long
E/ANR_LOG (17710): Blocked msg = { when=-15s378ms what=0 target=android.os.Handler callback=io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$6ZD1MYkhaLxyPjtoFDxe45u43DI } , cost = 15378 ms
E/ANR_LOG (17710): >>>Current msg List is:
E/ANR_LOG (17710): >>>CURRENT MSG DUMP OVER<<<

**Comment by jaydangar** [comment]
I would recommend checking the [chaquopy's official github](https://github.com/chaquo/chaquopy/issues) section in order to get the answer, as It might help. this issue might be regarding chaquopy SDK and not the plugin and the creator of the chaquopy official SDK might help you resolve this issue.
