### ISSUE TITLE
not working after getting the package

### ISSUE THREAD

**Issue by GeekyBharat99** [jaydangar/chaquopy_flutter#19]
C:\Users\bhara\OneDrive\Desktop\hack\bt_jam\android\app\src\debug\AndroidManifest.xml Error:
        Attribute application@name value=(android.app.Application) from (unknown)
        is also present at [:chaquopy] AndroidManifest.xml:7:18-72 value=(com.chaquo.python.android.PyApplication).
        Suggestion: add 'tools:replace="android:name"' to <application> element at AndroidManifest.xml:3:4-33:19 to override.  

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed : Attribute application@name value=(android.app.Application) from (unknown)
        is also present at [:chaquopy] AndroidManifest.xml:7:18-72 value=(com.chaquo.python.android.PyApplication).
        Suggestion: add 'tools:replace="android:name"' to <application> element at AndroidManifest.xml:3:4-33:19 to override

**Comment by jaydangar** [comment]
@GeekyBharat99 You can try adding 'tools:replace="android:name"' to element at AndroidManifest.xml:3:4-33:19 to override.

**Comment by GeekyBharat99** [comment]
That is fixed , but now its saying
"cannot use genericplatform on android. call python.start(new
androidplatform(context)) before using python, or use pyapplication to do
this automatically. "

Now what to do.

**Comment by jaydangar** [comment]
It means that you need to add `android:name="com.chaquo.python.android.PyApplication"` under application tag of your androidmanifest.xml file.

**Comment by GeekyBharat99** [comment]
Ok, thanks.
