### ISSUE TITLE
Is the app supposed to crash as soon as you open it if no license key is provided?

### ISSUE THREAD

**Issue by f-person** [jaydangar/chaquopy_flutter#21]
At first, I had trouble building the app – logs were complaining that both my app and the plugin define `android:name` in `AndroidManifest.xml`. After I changed it to `"com.chaquo.python.android.PyApplication"`, the app started crashing with the following message:

<img width="274" alt="image" src="https://user-images.githubusercontent.com/31893391/153663186-f57f3844-f128-4a3a-acb4-bb06619f3463.png">

**Comment by f-person** [comment]
BTW, I also tried adding `tools:replace="android:name"`. This way the app was building but executing Python code was giving errors this way

**Comment by f-person** [comment]
This looks like #19 – I was getting the same error

**Comment by jaydangar** [comment]
@f-person Can you check official[ setup instruction](https://chaquo.com/chaquopy/doc/current/android.html) of Chaquopy and check if it helps? You can also checkout the issue section of [chaquopy](https://github.com/chaquo/chaquopy/issues) to get more help on this issue.
