### ISSUE TITLE
Chaquopy flutter setup issue

### ISSUE THREAD

**Issue by varunlohade** [jaydangar/chaquopy_flutter#23]
I am trying to use this plugin but I am facing this issue.
![image](https://user-images.githubusercontent.com/50517140/160252265-482fa642-11e2-4147-8f1c-947c8d3bc3a3.png)
Can you please fix this issue?
or help me understand what maybe the cause.

**Comment by jaydangar** [comment]
add this line to application tag in manifest file `android:name="com.chaquo.python.android.PyApplication"`.
