### ISSUE TITLE
How to call python methods with 2 arguments 

### ISSUE THREAD

**Issue by vishalideastoimpact** [jaydangar/chaquopy_flutter#26]
String code "def method():\n"
    code +="   A = 10\nB=5\n"
    code +="   return A+B"
     code +="  method() "
 
   **final _result = await Chaquopy.executeCode(code);**
 
 **_result['textOutputOrError']**  is giving me **null**

**if i call method in print then it give me output in string** 
String code "def method():\n"
    code +="   A = 10\nB=5\n"
    code +="   return A+B"
**code +="print(method())"**

output is: **15 in string,** but it should be **int**

**My original program I'm returning dictionary with key as String and value as List from program**

**As per your docs Chaquopy.executeCode(code) should return output in a Map but it is returning String**

**Comment by jaydangar** [comment]
@vishalideastoimpact You can just assign your script in a single string and put it as a static code, so instead of writing the code as 

```
String code "def method():\n"
code +=" A = 10\nB=5\n"
code +=" return A+B"
code +=" method() "

final _result = await Chaquopy.executeCode(code);
```

you can just do following : 

```
String code  = "def method():
    A = 10
    B = 10
    return A+B
print(method())"

final _result = await Chaquopy.executeCode(code);
print(_result)
```

**Comment by vishalideastoimpact** [comment]
It doesn't work this way
String code  = "def method():
    A = 10
    B = 10
    return A+B
print(method())"

this is not way create python code into String
It gives errors

I think you dont understand the issue
Let me explain again:
 
1. Programm is working fine in my way
2. **_result['textOutputOrError']**  should contains map not String
3. As Chaquopy.executeCode(code); return a Map
