### ISSUE TITLE
How to return the output as a Map not as String ?

### ISSUE THREAD

**Issue by vishalideastoimpact** [jaydangar/chaquopy_flutter#27]
I want to receive the output in Map .**ie _result['textOutputOrError'] value must be a map.**
but I'm receiving String ?

def method():
    "code"
    dict['a']="ListA"
    dict['b']="ListB"
    return  dict
print(method) // **result['textOutputOrError'] contains value in string, I want value in a map**

**// I don't write print(method) output value is null**

**Comment by jaydangar** [comment]
The sole purpose of this library is to run any python script. can you try out this [example](https://pub.dev/packages/chaquopy/example) code and see if the script runs or not? The problem with the current script is that you need to be sure about the indentation errors which is pretty hard to identify with static scripts.

**Comment by vishalideastoimpact** [comment]
My script is running perfectly fine.
I just want to recive output in Map not in string

**Comment by vishalideastoimpact** [comment]
result['textOutputOrError'] is { 'a': [0,1,2] ,'b': [0,1,2],'c': [0,1,2],} as String I want it as map

**Comment by jaydangar** [comment]
@vishalideastoimpact the thing is that, this library is for running the python script that you provide as an input and returns the output string. If you want to do the processing on the output code, you need to provide final script which performs all the operations.

**Comment by vishalideastoimpact** [comment]
can Tell how to do that? if you have any example so

**Comment by jaydangar** [comment]
Instead of printing whole dictionary via using `print(method)`, you can just use `print(method()['a'])`, this will just print the value associated with key 'a', whatever processing you want, you can put it in a single python script.

**Comment by vishalideastoimpact** [comment]
I have multiple Key: value in my map

________________________________

**Comment by vishalideastoimpact** [comment]
I have found Work around.
What I have done is 
1. Replace single Quotes with double Quotes
2. Use json Decode to convert json String  to Map
