### ISSUE TITLE
Accessing files

### ISSUE THREAD

**Issue by rsudec** [jaydangar/chaquopy_flutter#3]
According to [Chaquopy docs](https://chaquo.com/chaquopy/doc/current/android.html#data-files) we should be able to open/read/use files.

All files should be stored in the `app/src/main/python` folder

 Then, to open the file at runtime, we can get the path using `__file__` that refers us to the `python` folder.

What I did, I set my file in that folder, beside the `script.py`. 

When I execute the code, trying to get the path: 

```
from os.path import dirname, join
print(join(dirname(__file__), 'dataset.csv'))
```

It results in an error message
`name '__file__' is not defined`

In Flutter I am writing the code inside """  """ (multiline string), but I don't think that is the problem.

How should I go about loading a file?
Thanks

**Comment by jaydangar** [comment]
You can try following solutions, instead of join(dirname(__file__)): 

```
join(os.getcwd())
join(sys.argv[0])
join(os.path.dirname(os.path.realpath('__file__')))
```

**Comment by jaydangar** [comment]
@rsudec I am closing this issue as of now. feel free to reopen it if this solution doesn't resolve your problem.
