### ISSUE TITLE
Flutter Build Failed

### ISSUE THREAD

**Issue by albert19a** [jaydangar/chaquopy_flutter#30]
Hi, I'm interested in your plugin and tried to use it. I'm working with VSCode in Windows 10 Home, target is an Android S21.

I created a new APP in flutter, the counter app, and I did not add any line that calls your package, just added all the configuration steps indicated in your readme file, just to set up and check that every thing goes.

I had to change this: _classpath "com.chaquo.python:gradle:latest-version"_
into this: _classpath 'com.chaquo.python:gradle:12.0.0'_
because it was not capable to resolve it.

When I run Start debugging I get an error, can you please help?

I paste here the debug console output ----->

Launching lib\main.dart on SM G991B in debug mode...
lib\main.dart:1
**e: C:\Portable\flutter\.pub-cache\hosted\pub.dartlang.org\chaquopy-0.0.16\android\src\main\kotlin\com\chaquopy\chaquopy\ChaquopyPlugin.kt: (51, 36): Type mismatch: inferred type is String? but String was expected
e: C:\Portable\flutter\.pub-cache\hosted\pub.dartlang.org\chaquopy-0.0.16\android\src\main\kotlin\com\chaquopy\chaquopy\ChaquopyPlugin.kt: (51, 41): Type mismatch: inferred type is String? but String was expected**

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':chaquopy:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 8s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by davidyuk** [comment]
I've had the same problem, as a workaround fixed it by changing
```diff
-val code: String = call.arguments()
+val code: String = call.arguments() ?: ""
```
in ChaquopyPlugin.kt

**Comment by albert19a** [comment]
Thank you very much, that solved the build problem!

**Comment by jaydangar** [comment]
@davidyuk Thanks for your solution, I have pushed a new update and mentioned your contribution.
