### ISSUE TITLE
Is OpenCV still not supported?

### ISSUE THREAD

**Issue by sharpordie** [jaydangar/chaquopy_flutter#32]
Your README indicates that it is not compatible with OpenCV but Chaquopy is now FOSS, and the README is still mentioning it requires license.

So is OpenCV working now? And if not are you working on it?

**Comment by jaydangar** [comment]
If the Chaquopy is free and open source, then Chaquopy plugin would not require any changes, you can absolutely use the FOSS Chaquopy with the latest version. I'll update the README for more clarification. I am working on the CHAQUOPY OpenCV project, stay tuned for more updates to come.

**Comment by sharpordie** [comment]
Amazing! I'm eagerly awaiting it. ;)
