### ISSUE TITLE
I/flutter (16332): ModuleNotFoundError: No module named 'script'

### ISSUE THREAD

**Issue by asks1012** [jaydangar/chaquopy_flutter#33]
I'm getting the above error when trying to use the chaquopy to run the following python code :

import numpy as np
nums = np.array([2, 3, 4, 5, 6])
nums2 = nums + 2
print(nums2)

**Comment by jaydangar** [comment]
@asks1012 #8 is the same issue.

**Comment by asks1012** [comment]
Thank you for your response.
Can I run flask server on mobile using this package?
Is the support for opencv and matplotlib package added?
