### ISSUE TITLE
no module named script

### ISSUE THREAD

**Issue by amirhossein-mlkz** [jaydangar/chaquopy_flutter#35]
Hello, I Run the example code and got a "No module name script" error when I click on the "run code button". I download script.py and put it in all python directories in the project and again I get this error. I followed all steps in "Read Me". please help me

**Comment by jaydangar** [comment]
make sure you're syncing your gradle, after you put code.py in the python directory. The error means that it's not able to find the code.py file. Also make sure you're doing all the steps without skipping any of the steps.
