### ISSUE TITLE
Run python file instead of code

### ISSUE THREAD

**Issue by VimeshPolaris** [jaydangar/chaquopy_flutter#38]
Hello,
I want to use the python file instead of code in Chaquopy.executeCode() method.
Can I access that file using the Flutter assets path?

My code looks like this,

`final result = await Chaquopy.executeCode('python assets/py_files/btl_host.py -v -i /dev/cu.usbserial-0001 -d samd2x -a 0x800 -f assets/py_files/BK_8M_HG_1_0.X.production.bin');`

**Comment by jaydangar** [comment]
You can checkout how to access the file from [here](https://chaquo.com/chaquopy/doc/12.0/faq.html).
