### ISSUE TITLE
Syncing the project does not create a python folder

### ISSUE THREAD

**Issue by Stacey-Koornneef** [jaydangar/chaquopy_flutter#39]
After following the tutorial at https://pub.dev/packages/chaquopy I can't get the app to create a python folder after syncing.  I have created one myself and added the python script to it, but the example does not recognize the script and receives this error on the emulator screen: "This shows Output or Error: ModuleNotFoundError: No module named 'script'"

**Comment by jaydangar** [comment]
It should create python folder, otherwise it'll be considered build failure. I would recommend trying to resolve the configuration issues first.
