### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by furkan59** [jaydangar/chaquopy_flutter#4]
Hi,

When I add this library to my project. Android studio says 

"The library 'package:chaquopy/chaquopy.dart' is legacy, and should not be imported into a null safe library."

Are you planning to make a version for null safety ?

**Comment by jaydangar** [comment]
Yes soon I'll add null safety.

**Comment by jaydangar** [comment]
@furkan59  Just a quick update, I have just added the null safety feature and uploaded the new version of this plugin. So, once review is finished it'll be available for use.
