### ISSUE TITLE
Not able to execute Chaquopy.executeCode(code) in Isolate

### ISSUE THREAD

**Issue by PremchandGat** [jaydangar/chaquopy_flutter#40]
### **Trying to run Chaquopy.executeCode(code) in Isolate**

```
void isolateForReceiveData(SendPort sendPort) async {
  print("ISOLATE STARTED NOW");

  /// Set up a receiver port for Mike
  ReceivePort receivePort = ReceivePort();

  /// Send Mike receivePort sendPort via mySendPort
  sendPort.send(receivePort.sendPort);
  receivePort.listen((message) async {
var x = await Chaquopy.executeCode(message);
return x;
  });
}
```
OUTPUT:
E/flutter ( 6900): [ERROR:flutter/runtime/dart_isolate.cc(1098)] Unhandled exception:
E/flutter ( 6900): Binding has not yet been initialized.
E/flutter ( 6900): The "instance" getter on the ServicesBinding binding mixin is only available once that binding has been initialized.
E/flutter ( 6900): Typically, this is done by calling "WidgetsFlutterBinding.ensureInitialized()" or "runApp()" (the latter calls the former). Typically this call is done in the "void main()" method. The "ensureInitialized" method is idempotent; calling it multiple times is not harmful. After calling that method, the "instance" getter will return the binding.
E/flutter ( 6900): In a test, one can call "TestWidgetsFlutterBinding.ensureInitialized()" as the first line in the test's "main()" method to initialize the binding.
E/flutter ( 6900): If ServicesBinding is a custom binding mixin, there must also be a custom binding class, like WidgetsFlutterBinding, but that mixes in the selected binding, and that is the class that must be constructed before using the "instance" getter.
E/flutter ( 6900): #0      BindingBase.checkInstance.<anonymous closure>
package:flutter/…/foundation/binding.dart:284
E/flutter ( 6900): #1      BindingBase.checkInstance
package:flutter/…/foundation/binding.dart:366
E/flutter ( 6900): #2      ServicesBinding.instance
package:flutter/…/services/binding.dart:54
E/flutter ( 6900): #3      MethodChannel.binaryMessenger
package:flutter/…/services/platform_channel.dart:254
E/flutter ( 6900): #4      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:289
E/flutter ( 6900): #5      MethodChannel.invokeMethod
package:flutter/…/services/platform_channel.dart:472
E/flutter ( 6900): #6      Chaquopy.executeCode
package:chaquopy/chaquopy.dart:13
E/flutter ( 6900): #7      isolateForReceiveData.<anonymous closure>
package:bluetoothapp/model/python.dart:53
E/flutter ( 6900): #8      _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter ( 6900): #9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter ( 6900): #10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter ( 6900): #11     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
E/flutter ( 6900): #12     _StreamController._add (dart:async/stream_controller.dart:648:7)
E/flutter ( 6900): #13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)

**Comment by padukadafa** [comment]
try add WidgetsFlutterBinding.ensureInitialized() in main function

```dart
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(MyApp());
}
```

**Comment by PremchandGat** [comment]
Already have this in my main function still not running

**Comment by jaydangar** [comment]
The code runs in a separate thread already, do you really need isolate? I kept this in mind, while creating the library.
