### ISSUE TITLE
How to sync project to automatically create the Python folder?

### ISSUE THREAD

**Issue by athenawisdoms** [jaydangar/chaquopy_flutter#44]
The README instructions says

> After that sync your project.
> 
> Now, in your android folder, you'll have additional python folder created.

How do you "sync your project"? Where should this `python` directory be located?

## Attempt 1

I opened up the `android` directory in Android Studio, then in Android Studio I clicked on `File > Sync Project with Gradle Files`. However, no `python` directory was created inside the `android` directory.

## Attempt 2

From vscode, I build and ran my Flutter app by running `Run > Start Debugging`. I can see debug messages about Chaquopy installing pip packages (I have configured this in `build.gradle`) but still no `python` directory created anywhere.

I did recall seeing a `python` directory sometime before I got Chaquopy properly setup, (before attempts 1 and 2 above) and had deleted it. Perhaps there is a cache somewhere that says that this `python` directory has been created before, and there is no need to create it again?

Hope someone can help me, thank you.

**Comment by narayan954** [comment]
> The README instructions says
> 
> > After that sync your project.
> > Now, in your android folder, you'll have additional python folder created.
> 
> How do you "sync your project"? Where should this `python` directory be located?
> 
> ## Attempt 1
> I opened up the `android` directory in Android Studio, then in Android Studio I clicked on `File > Sync Project with Gradle Files`. However, no `python` directory was created inside the `android` directory.
> 
> ## Attempt 2
> From vscode, I build and ran my Flutter app by running `Run > Start Debugging`. I can see debug messages about Chaquopy installing pip packages (I have configured this in `build.gradle`) but still no `python` directory created anywhere.
> 
> I did recall seeing a `python` directory sometime before I got Chaquopy properly setup, (before attempts 1 and 2 above) and had deleted it. Perhaps there is a cache somewhere that says that this `python` directory has been created before, and there is no need to create it again?
> 
> Hope someone can help me, thank you.

Were you able to Sync Project with Gradle Files successfully? Cuz when I tried to do that, I got an error 
`sh
Build file 'D:\flutter_chaquopy\android\app\build.gradle' line: 5

An exception occurred applying plugin request [id: 'com.chaquo.python']
> Failed to apply plugin 'com.chaquo.python'.
   > Failed to find plugin com.android.tools.build:gradle

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.plugins.InvalidPluginException: An exception occurred applying plugin request [id: 'com.chaquo.python']
`

I thought it might be due to my version, but I double checked the versions 
7.5 for gradle and 15.0.1 for chaquopy. And according to the [official website](https://chaquo.com/chaquopy/doc/current/versions.html), they seem compatible.

**Comment by jaydangar** [comment]
please use the latest version, and update here. Closing the issue for now.
