### ISSUE TITLE
Pass list of images as argument to the python code.

### ISSUE THREAD

**Issue by the-dev7** [jaydangar/chaquopy_flutter#46]
I'm not able to pass any arguments [variables stored in flutter] directly to the python code via this plugin as executeCode() doesn't allow arguments to be passed separately.

The data is a list of images stored as a single variable.

Can you suggest a workaround?

**Comment by jaydangar** [comment]
You might want to take a look at this example code : https://github.com/jaydangar/dcodeai_playground
