### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by ahsan1246** [jaydangar/chaquopy_flutter#48]
1: Task failed with an exception.
-----------
* Where:
Build file '/Users/mac/.pub-cache/hosted/pub.dev/chaquopy-0.0.18/android/build.gradle' line: 28

* What went wrong:
A problem occurred evaluating project ':chaquopy'.
> Failed to apply plugin 'com.chaquo.python'.
   > Could not find matching constructor for: com.android.build.gradle.internal.api.DefaultAndroidSourceDirectorySet(String, org.gradle.api.internal.project.DefaultProject_Decorated, com.android.build.gradle.internal.api.artifact.SourceArtifactType$JAVA_SOURCES)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* Where:
Script '/Users/mac/fvm/versions/3.7.12/packages/flutter_tools/gradle/flutter.gradle' line: 390

* What went wrong:
A problem occurred configuring project ':chaquopy'.
> Failed to notify project evaluation listener.
   > Could not find matching constructor for: com.android.build.gradle.internal.api.DefaultAndroidSourceDirectorySet(String, org.gradle.api.internal.project.DefaultProject_Decorated, com.android.build.gradle.internal.api.artifact.SourceArtifactType$JAVA_SOURCES)
   > Cannot invoke method substring() on null object
   > com.android.builder.errors.EvalIssueException: compileSdkVersion is not specified. Please add it to build.gradle

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

**Comment by Md-Sifatullah617** [comment]
same problem have anyone find out how to solve the question

**Comment by jaydangar** [comment]
This Problem is resolved in the newer version, kindly use latest version of chaquopy.
