### ISSUE TITLE
OpenCV and matplotlib

### ISSUE THREAD

**Issue by ChiatanyaChakka** [jaydangar/chaquopy_flutter#5]
Thank you for such a great plugin... Is the support for opencv and matplotlib enabled yet?

**Comment by jaydangar** [comment]
It does support it but problem is that, it needs different configuration and also it needs to use a predefined variable only, for input and output. see this app I have developed using chaquopy and flutter, which runs nltk, scipy, numpy, matplotlib, cv libraries https://play.google.com/store/apps/details?id=com.dcodeai.dcodeai_playground

**Comment by ChiatanyaChakka** [comment]
I'm new to using flutter so can you elaborate a little more?
Thanks in advance

**Comment by jaydangar** [comment]
you can download the provided app and you can see that for running Matplotlib or CV code the loading of image and showing the output of the code is already written. so you are forced to use provided variable name as given in the input and output. I highy recommend you to tryout the app to better understand.
