### ISSUE TITLE
Use python file in flutter app ? calling issue.

### ISSUE THREAD

**Issue by ps2229** [jaydangar/chaquopy_flutter#6]
How would you load a .py file into this function and then call the func in .py file from the flutter application using the chaquopy.executeCode()???? and if possible could you help me with the example of the same as well.thank you

**Comment by jaydangar** [comment]
check this answer on stackoverflow. https://stackoverflow.com/questions/54122850/how-to-read-and-write-a-text-file-in-flutter

**Comment by ps2229** [comment]
> check this answer on stackoverflow. this is about reading a txt file, I am not sure if it works same for py or not. if possible save your code in txt file only and use this code to read and run code using chaquopy. https://stackoverflow.com/questions/54122850/how-to-read-and-write-a-text-file-in-flutter

But in the pub-dev document they have saved the python file as script.py then called the file using chaquopy.executeCode not the text format then get the result in the form of maps, I have this doudt of how to call the script.py file ,been stuck at this for days now.
https://pub.dev/packages/chaquopy

**Comment by jaydangar** [comment]
you need to define the python file in 'pubspec.yaml'. then you can define a path and use that file.

**Comment by ps2229** [comment]
> you need to define the python file in 'pubspec.yaml'. then you can define a path and use that file.

where in the pubspec.yaml file I have already added the plugins and the dependencies , an example would be really appreciated of adding the file and a simple print statement or hello world would be good, not really a pro in flutter

**Comment by jaydangar** [comment]
@ps2229 this is not a right platform related to your queries, ask onto the forums like stackoverflow, google, as such. closing this issue as it's not related to chaquopy.
