### ISSUE TITLE
Issue while running this example

### ISSUE THREAD

**Issue by ps2229** [jaydangar/chaquopy_flutter#7]
Whenever I try to run this example this error pops while running any python statement in the app 
Error: MissingPluginException(No implementation found for method runPythonScript on channel chaquopy)
 at Object.throw_ [as throw] (http://localhost:59989/dart_sdk.js:5348:11)
    at MethodChannel._invokeMethod (http://localhost:59989/packages/flutter/src/services/system_channels.dart.lib.js:962:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:59989/dart_sdk.js:39230:33
    at _RootZone.runUnary (http://localhost:59989/dart_sdk.js:39087:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:59989/dart_sdk.js:34073:29)
    at handleValueCallback (http://localhost:59989/dart_sdk.js:34633:49)
    at Function._propagateToListeners (http://localhost:59989/dart_sdk.js:34671:17)
    at _Future.new.[_completeWithValue] (http://localhost:59989/dart_sdk.js:34513:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:59989/dart_sdk.js:34536:35)
    at Object._microtaskLoop (http://localhost:59989/dart_sdk.js:39374:13)
    at _startMicrotaskLoop (http://localhost:59989/dart_sdk.js:39380:13)
    at http://localhost:59989/dart_sdk.js:34887:9
any solution to this??

**Comment by jaydangar** [comment]
can you post all the code?

**Comment by ps2229** [comment]
Nope Script.py is same didnt even touch it just downloaded it and put it into the python file in the project
pubspec.yaml
name: try_chaq
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  chaquopy: ^0.0.9
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  plugin:
    platforms:
      android:
        package: com.chaquopy.chaquopy
        pluginClass: ChaquopyPlugin

app/build.gradle
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}
def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}
def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}
def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'com.android.application'
apply plugin: 'com.chaquo.python'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 30

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }
    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.try_chaq"
        minSdkVersion 16
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        ndk {
            abiFilters "armeabi-v7a","x86"
        }
        python {

            buildPython "C:/Users/prakhar12/AppData/Local/Programs/Python/Python38/python.exe"

            pip {
                install "numpy==1.17.4"
                install "pandas==0.25.3"
            }
        }
        android {
            sourceSets {
                main {
                    python.srcDir "src/main/python"
                }
            }
        }
    }
    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}
flutter {
    source '../..'
}
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}

android/gradle
package android

buildscript {
    ext.kotlin_version = '1.4.31'
    repositories {
        google()
        jcenter()
        maven { url "https://chaquo.com/maven" }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.0.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "com.chaquo.python:gradle:9.1.0"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
the main.dart and chaquopy.dart are the same as your example code , if you want I can mail the project files over to you as well if this isnt clear.

**Comment by jaydangar** [comment]
kindly sync gradle before use. you can do it by going into `android directory` and then running the following command 👍 

`./gradlew --refresh-dependencies`

**Comment by ps2229** [comment]
> kindly sync gradle before use. you can do it by going into `android directory` and then running the following command 👍
> 
> `./gradlew --refresh-dependencies`

I tried its showing this error
Build file 'C:\Users\prakhar12\StudioProjects\try_chaq\android\build.gradle' should not contain a package statement.

**Comment by ps2229** [comment]
> > kindly sync gradle before use. you can do it by going into `android directory` and then running the following command 👍
> > `./gradlew --refresh-dependencies`
> 
> I tried its showing this error
> Build file 'C:\Users\prakhar12\StudioProjects\try_chaq\android\build.gradle' should not contain a package statement.

The sync was succesful after I removed "package android" line from android/build.gradle but the error is still there

**Comment by jaydangar** [comment]
it's different issue, please resolve it on your own. This is for chaquopy_flutter plugin related bugs only. for android related help use stackoverflow. thanks.
