### ISSUE TITLE
No module named 'script'

### ISSUE THREAD

**Issue by dhananjay1710** [jaydangar/chaquopy_flutter#8]
Any advice on how to tackle this issue?

Also, thank you so much for coming up with a library like this !!! Genuinely very helpful!

**Comment by dhananjay1710** [comment]
Made a folder named 'python' inside Android/app/src/main
and pasted the script.py inside it

**Comment by jaydangar** [comment]
have you build the gradle before pasting the "script.py" file? kindly sync the gradle and let me know if it resolves your issue. also, if you like the plugin kindly star this repo, it would be really motivative for me. thanks.

**Comment by dhananjay1710** [comment]
Yes moving the script.py to the write directory and then rebuilding the gradle is what solved the issue for me. Could you also guide me as to where the python code is, so i can attempt to edit my own code into it? 

I have starred your repo, absolutely loved your work!

**Comment by jaydangar** [comment]
@dhananjay1710 I didn't get your point, what code do you want to edit? python script that you want to run on android device or python script that i wrote and you have loaded via "script.py" that will execute your python script from android device?

**Comment by dhananjay1710** [comment]
python code that I want to edit on my android device

**Comment by dhananjay1710** [comment]
nevermind, i went through your code, i think i have to make all necessary changes under the on pressed async function! Is it possible to return more than a text output?

**Comment by dhananjay1710** [comment]
As in right now I can type the python code into the app running on my device and get an output. What if there was a set python script that i wanted to run everytime a user clicked on a button? do i replace the 

chaquopy.executeCode(_controller.text) with chaquopy.executeCode("   -- my python script -- ")

**Comment by jaydangar** [comment]
yes, definitely you can put static code there.

**Comment by dhananjay1710** [comment]
thank you so much!

**Comment by dhananjay1710** [comment]
can one install and use pytorch?

**Comment by jaydangar** [comment]
@dhananjay1710  PyTorch you can install if it's not depending on images.

**Comment by jaydangar** [comment]
@dhananjay1710 please post your error here, also i think package name is pytorch not torch. kindly double check from your end.

**Comment by dhananjay1710** [comment]
package name is pytorch yes, but as far as im aware, the install command is pip install pytorch
ref: https://pypi.org/project/torch/

![Screenshot (166)](https://user-images.githubusercontent.com/42811038/126274927-72f74ee5-b9e0-4482-a43a-a24ccfdec713.png)

i think its more of a dependency needed to install pytorch, so a problem on my end really

**Comment by jaydangar** [comment]
@dhananjay1710 the error is about loading predefined models (I am not sure, but the file name it's looking for is "collect and distribute....zip file). So, it's better to use libraries which doesn't require any predefined libraries to load. kindly check any alternative libraries.
